organization = '177204'
project = 'PSRemoting-Test'
personal_access_token = 'G2JAC9cbPJqH6y7albiNkRwapB13gaQLtyWixOFeaS31h5kAQzwjJQQJ99BBACAAAAAe37ZBAAASAZDO1aX7'
new_pipeline_name = 'NewClassicPipeline5'
input_file = 'outputs/classic_pipeline_definition.json'